from .home import home_page
from .bebidas import bebidas_page
from .licores import licores_page
from .entradas import entradas_page
from .promociones import promociones_page
from .cocteles import cocteles_page
from .postres import postres_page
from .platos import platos_page
from .extras import extras_page
from .kids import kids_page
from .cafes import cafes_page
from .burger import burger_page
from .carrito import carrito_page